---
  TRADE_OPTIONS:
    # QUANTITY and PAIRING determine how much of your wallet value will be used to buy the new token.
    # 'QUANTITY: 15' and 'PAIRING: USDT' means you will spend 15 USDT to buy XXX_USDT where XXX is the new token.
    QUANTITY: 15
    PAIRING: USDT
    # Test mode. No real money will be used.
    TEST: True
    # Stop Loss in % of your buy value.
    SL: -3
    # Take Profit in % of your buy value.
    TP: 2
    # DO NOT DISABLE TSL!!!! YOUR BOT WILL NOT SELL
    ENABLE_TSL: True
    # Trailing Stop Loss
    TSL: -4
    # Trailing Take Profit
    TTP: 2
  LOGGING:
    # Logging levels used in this program are ERROR, INFO, and DEBUG
    LOG_LEVEL: INFO
    LOG_FILE: bot.log
    LOG_TO_CONSOLE: True
  TELEGRAM:
    # set to True to enable telegram notifications
    ENABLED: False
    # how to get a bot token: https://core.telegram.org/bots#6-botfather
    BOT_TOKEN: my_token
    # how to get your chatID:
    # find your bot and start a chat
    # go visit https://api.telegram.org/bot%3CTOKEN%3E/getUpdates and find the chat ID
    BOT_CHAT_ID: my_chat_id
